version: '2.0'
services:
  janus:
    build: .
    ports:
    - "8999:8888"
    volumes:
    - .:/code
    - logvolume01:/var/log
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - redis
  redis:
    image: redis
    ports:
        - "6378:6379"
volumes:
  logvolume01: {}