version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  upload:
    machine: true
    steps:
      - checkout
      - run: ./ci/set_aws_cred.sh
      - run: ./ci/get_params.sh
      - run: ./ci/push_docker_image.sh
      - run: ./ci/upload_eb_version.sh

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
        filters:
          tags:
            only: /^v.*/
      - upload:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
